[package]
name = "types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ast.workspace = true
token.workspace = true

[dev-dependencies]
lexer.workspace = true
parser.workspace = true
